<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstraction Layer\ServiceAbstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Configuration classes\" />
    <Folder Include="Data\Contexts\" />
    <Folder Include="Data\DataSeed\" />
    <Folder Include="Migrations\" />
    <Folder Include="Identity\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
